# used as prefix
project_name: utr3_quantification
# directory with bam files
bam_dir: ../test_data/
samplesheets_dir: ../test_data/samplesheets/
# reference annotation
annotation: /data/hilgers/group/rauer/APA_target_caller/apa_target_caller/Annotations/dm6_ensembl96.gtf
# original whippet nodes
segments: /data/hilgers/group/rauer/APA_target_caller/apa_target_caller/Annotations/Whippet_nodes.gff
# list of paqr/isoscm breakpoints (separated by space)
polya_database:
  /data/hilgers/group/rauer/APA_target_caller/apa_target_caller/PolyA_DB/Generic/PolyA_db.bed
# params for breakpoint filtering
min_distance: 100
padj_cutoff: 0.05
